// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"go_zero/apps/order/rpc/internal/logic"
	"go_zero/apps/order/rpc/internal/svc"
	"go_zero/apps/order/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Orders(ctx context.Context, in *pb.OrdersRequest) (*pb.OrdersResponse, error) {
	l := logic.NewOrdersLogic(ctx, s.svcCtx)
	return l.Orders(in)
}
