// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: rcp.proto

package rcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RcpClient is the client API for Rcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RcpClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rcpClient struct {
	cc grpc.ClientConnInterface
}

func NewRcpClient(cc grpc.ClientConnInterface) RcpClient {
	return &rcpClient{cc}
}

func (c *rcpClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rcp.Rcp/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RcpServer is the server API for Rcp service.
// All implementations must embed UnimplementedRcpServer
// for forward compatibility
type RcpServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRcpServer()
}

// UnimplementedRcpServer must be embedded to have forward compatible implementations.
type UnimplementedRcpServer struct {
}

func (UnimplementedRcpServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRcpServer) mustEmbedUnimplementedRcpServer() {}

// UnsafeRcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RcpServer will
// result in compilation errors.
type UnsafeRcpServer interface {
	mustEmbedUnimplementedRcpServer()
}

func RegisterRcpServer(s grpc.ServiceRegistrar, srv RcpServer) {
	s.RegisterService(&Rcp_ServiceDesc, srv)
}

func _Rcp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RcpServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rcp.Rcp/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RcpServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Rcp_ServiceDesc is the grpc.ServiceDesc for Rcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rcp.Rcp",
	HandlerType: (*RcpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Rcp_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcp.proto",
}
