// Code generated by goctl. DO NOT EDIT!
// Source: rcp.proto

package server

import (
	"context"

	"go_zero/apps/product/rcp/internal/logic"
	"go_zero/apps/product/rcp/internal/svc"
	"go_zero/apps/product/rcp/rcp"
)

type RcpServer struct {
	svcCtx *svc.ServiceContext
	rcp.UnimplementedRcpServer
}

func NewRcpServer(svcCtx *svc.ServiceContext) *RcpServer {
	return &RcpServer{
		svcCtx: svcCtx,
	}
}

func (s *RcpServer) Ping(ctx context.Context, in *rcp.Request) (*rcp.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
